export const BUSINESS_TYPES = [
  'Freelancer','Consultant','Artisan','Agency','Startup','Small Business',
  'Investor','NGO','Educational Institution','Healthcare Provider',
  'Retail Business','Manufacturing','Real Estate','Food & Catering',
  'Events & Planning','Transportation','Construction','Agriculture',
  'Media & PR','Technology','Fashion & Clothing','Photography',
  'Videography','Hair & Beauty','Coaching & Training','Legal Services','Other',
]

export const BUSINESS_TITLES = [
  'Product Manager','Software Developer','Graphic Designer','Fashion Designer',
  'Accountant','Lawyer','Tutor','Photographer','Videographer','Digital Marketer',
  'Restaurant Owner','Contractor','Mechanic','Electrician','Architect',
  'Consultant','Doctor','Nurse','Pharmacist','Dentist','Therapist',
  'Interior Designer','Makeup Artist','Hair Stylist','Barber','Tailor',
  'Caterer','Event Planner','Musician','DJ','Actor','Content Creator',
  'Real Estate Agent','Insurance Agent','Financial Advisor','Coach',
  'Teacher','Lecturer','Engineer','Data Analyst','UI/UX Designer',
  'Copywriter','Translator','Driver','Logistics Manager','Farmer','Other',
]

export const CURRENCIES = [
  {code:'NGN',label:'Nigerian Naira (₦)'},
  {code:'USD',label:'US Dollar ($)'},
  {code:'GBP',label:'British Pound (£)'},
  {code:'EUR',label:'Euro (€)'},
  {code:'GHS',label:'Ghanaian Cedi (GH₵)'},
  {code:'KES',label:'Kenyan Shilling (KSh)'},
  {code:'ZAR',label:'South African Rand (R)'},
  {code:'AED',label:'UAE Dirham (AED)'},
  {code:'SAR',label:'Saudi Riyal (SAR)'},
  {code:'CAD',label:'Canadian Dollar (CA$)'},
  {code:'AUD',label:'Australian Dollar (A$)'},
  {code:'INR',label:'Indian Rupee (₹)'},
  {code:'EGP',label:'Egyptian Pound (EGP)'},
  {code:'MAD',label:'Moroccan Dirham (MAD)'},
  {code:'XOF',label:'West African CFA Franc (XOF)'},
]

export const CURRENCY_NAMES: Record<string,string> = {
  NGN:'Nigerian Naira (₦)', USD:'US Dollar ($)', GBP:'British Pound (£)',
  EUR:'Euro (€)', GHS:'Ghanaian Cedi (GH₵)', KES:'Kenyan Shilling (KSh)',
  ZAR:'South African Rand (R)', AED:'UAE Dirham (AED)', SAR:'Saudi Riyal (SAR)',
  CAD:'Canadian Dollar (CA$)', AUD:'Australian Dollar (A$)', INR:'Indian Rupee (₹)',
  EGP:'Egyptian Pound (EGP)', MAD:'Moroccan Dirham (MAD)', XOF:'West African CFA Franc',
}

export const COUNTRY_CURRENCY_MAP: Record<string,string> = {
  NG:'NGN',US:'USD',GB:'GBP',GH:'GHS',KE:'KES',ZA:'ZAR',
  AE:'AED',SA:'SAR',CA:'CAD',AU:'AUD',IN:'INR',EG:'EGP',MA:'MAD',
}

export const COUNTRY_BANKS: Record<string, string[]> = {
  NG: ['Access Bank','GTBank (Guaranty Trust Bank)','Zenith Bank','First Bank of Nigeria',
       'UBA (United Bank for Africa)','OPay','Fidelity Bank','Stanbic IBTC Bank',
       'Wema Bank','Moniepoint','Kuda Bank','Palmpay','Polaris Bank',
       'Sterling Bank','Union Bank','Ecobank Nigeria','FCMB','Keystone Bank'],
  AE: ['Emirates NBD','ADCB (Abu Dhabi Commercial Bank)','FAB (First Abu Dhabi Bank)',
       'Mashreq Bank','RAK Bank','Dubai Islamic Bank','ENBD','Citibank UAE',
       'HSBC UAE','Standard Chartered UAE'],
  GB: ['Barclays','HSBC UK','Lloyds Bank','NatWest','Santander UK','Halifax',
       'Nationwide','Monzo','Revolut','Starling Bank'],
  US: ['Chase','Bank of America','Wells Fargo','Citibank','US Bank',
       'Goldman Sachs','Capital One','TD Bank','PNC Bank','Ally Bank'],
  GH: ['GCB Bank','Ecobank Ghana','Absa Bank Ghana','Zenith Bank Ghana',
       'MTN Mobile Money','Vodafone Cash','AirtelTigo Money','Fidelity Bank Ghana'],
  KE: ['KCB Bank','Equity Bank','Co-operative Bank','Standard Chartered Kenya',
       'Absa Bank Kenya','NCBA Bank','M-Pesa','Safaricom','I&M Bank'],
  ZA: ['Standard Bank','FNB (First National Bank)','Absa','Nedbank',
       'Capitec Bank','Investec','African Bank','TymeBank'],
  DEFAULT: ['Local Bank','Commercial Bank','Savings Bank','Cooperative Bank','Other'],
}

export const COUNTRY_STATES: Record<string, string[]> = {
  NG: ['Abia','Adamawa','Akwa Ibom','Anambra','Bauchi','Bayelsa','Benue','Borno',
       'Cross River','Delta','Ebonyi','Edo','Ekiti','Enugu','FCT (Abuja)',
       'Gombe','Imo','Jigawa','Kaduna','Kano','Katsina','Kebbi','Kogi',
       'Kwara','Lagos','Nasarawa','Niger','Ogun','Ondo','Osun','Oyo',
       'Plateau','Rivers','Sokoto','Taraba','Yobe','Zamfara'],
  GH: ['Ashanti','Brong-Ahafo','Central','Eastern','Greater Accra',
       'Northern','Upper East','Upper West','Volta','Western'],
  KE: ['Nairobi','Mombasa','Kisumu','Nakuru','Eldoret','Thika','Malindi',
       'Kitale','Garissa','Kakamega'],
  ZA: ['Eastern Cape','Free State','Gauteng','KwaZulu-Natal','Limpopo',
       'Mpumalanga','North West','Northern Cape','Western Cape'],
  AE: ['Abu Dhabi','Dubai','Sharjah','Ajman','Ras Al Khaimah','Fujairah','Umm Al Quwain'],
  US: ['Alabama','Alaska','Arizona','Arkansas','California','Colorado',
       'Connecticut','Delaware','Florida','Georgia','Hawaii','Idaho',
       'Illinois','Indiana','Iowa','Kansas','Kentucky','Louisiana',
       'Maine','Maryland','Massachusetts','Michigan','Minnesota',
       'Mississippi','Missouri','Montana','Nebraska','Nevada',
       'New Hampshire','New Jersey','New Mexico','New York',
       'North Carolina','North Dakota','Ohio','Oklahoma','Oregon',
       'Pennsylvania','Rhode Island','South Carolina','South Dakota',
       'Tennessee','Texas','Utah','Vermont','Virginia','Washington',
       'West Virginia','Wisconsin','Wyoming'],
  GB: ['England','Scotland','Wales','Northern Ireland'],
  DEFAULT: [],
}

// LGAs per Nigerian state — complete 774 LGAs + key global cities
export const STATE_CITIES: Record<string, string[]> = {
  // ── NIGERIA — complete LGA lists ──────────────────────────────
  'Lagos': [
    'Agege','Ajeromi-Ifelodun','Alimosho','Amuwo-Odofin','Apapa',
    'Badagry','Epe','Eti-Osa','Ibeju-Lekki','Ifako-Ijaye',
    'Ikeja','Ikorodu','Kosofe','Lagos Island','Lagos Mainland',
    'Mushin','Ojo','Oshodi-Isolo','Shomolu','Somolu','Surulere','Other',
  ],
  'Abuja': [
    'Abaji','Abuja Municipal Area Council (AMAC)','Bwari','Gwagwalada',
    'Kuje','Kwali','Other',
  ],
  'FCT (Abuja)': [
    'Abaji','Abuja Municipal Area Council (AMAC)','Bwari','Gwagwalada',
    'Kuje','Kwali','Other',
  ],
  'Abia': [
    'Aba North','Aba South','Arochukwu','Bende','Ikwuano',
    'Isiala Ngwa North','Isiala Ngwa South','Isuikwuato','Obi Ngwa',
    'Ohafia','Osisioma','Ugwunagbo','Ukwa East','Ukwa West',
    'Umuahia North','Umuahia South','Umu Nneochi','Other',
  ],
  'Adamawa': [
    'Demsa','Fufure','Ganye','Gayuk','Gombi','Grie','Hong','Jada',
    'Lamurde','Madagali','Maiha','Mayo-Belwa','Michika','Mubi North',
    'Mubi South','Numan','Shelleng','Song','Toungo','Yola North',
    'Yola South','Other',
  ],
  'Akwa Ibom': [
    'Abak','Eastern Obolo','Eket','Esit Eket','Essien Udim','Etim Ekpo',
    'Etinan','Ibeno','Ibesikpo Asutan','Ibiono-Ibom','Ika','Ikono',
    'Ikot Abasi','Ikot Ekpene','Ini','Itu','Mbo','Mkpat-Enin',
    'Nsit-Atai','Nsit-Ibom','Nsit-Ubium','Obot Akara','Okobo','Onna',
    'Oron','Oruk Anam','Udung-Uko','Ukanafun','Uruan','Urue-Offong/Oruko',
    'Uyo','Other',
  ],
  'Anambra': [
    'Aguata','Anambra East','Anambra West','Anaocha','Awka North',
    'Awka South','Ayamelum','Dunukofia','Ekwusigo','Idemili North',
    'Idemili South','Ihiala','Njikoka','Nnewi North','Nnewi South',
    'Ogbaru','Onitsha North','Onitsha South','Orumba North','Orumba South',
    'Oyi','Other',
  ],
  'Bauchi': [
    'Alkaleri','Bauchi','Bogoro','Damban','Darazo','Dass','Gamawa',
    'Ganjuwa','Giade','Itas/Gadau','Jama\'are','Katagum','Kirfi',
    'Misau','Ningi','Shira','Tafawa Balewa','Toro','Warji','Zaki','Other',
  ],
  'Bayelsa': [
    'Brass','Ekeremor','Kolokuma/Opokuma','Nembe','Ogbia',
    'Sagbama','Southern Ijaw','Yenagoa','Other',
  ],
  'Benue': [
    'Ado','Agatu','Apa','Buruku','Gboko','Guma','Gwer East','Gwer West',
    'Katsina-Ala','Konshisha','Kwande','Logo','Makurdi','Obi','Ogbadibo',
    'Ohimini','Oju','Okpokwu','Otukpo','Tarka','Ukum','Ushongo','Vandeikya',
    'Other',
  ],
  'Borno': [
    'Abadam','Askira/Uba','Bama','Bayo','Biu','Chibok','Damboa',
    'Dikwa','Gubio','Guzamala','Gwoza','Hawul','Jere','Kaga','Kala/Balge',
    'Konduga','Kukawa','Kwaya Kusar','Mafa','Magumeri','Maiduguri',
    'Marte','Mobbar','Monguno','Ngala','Nganzai','Shani','Other',
  ],
  'Cross River': [
    'Abi','Akamkpa','Akpabuyo','Bakassi','Bekwarra','Biase',
    'Boki','Calabar Municipal','Calabar South','Etung','Ikom',
    'Obanliku','Obubra','Obudu','Odukpani','Ogoja','Yakuur','Yala','Other',
  ],
  'Delta': [
    'Aniocha North','Aniocha South','Bomadi','Burutu','Ethiope East',
    'Ethiope West','Ika North East','Ika South','Isoko North','Isoko South',
    'Ndokwa East','Ndokwa West','Okpe','Oshimili North','Oshimili South',
    'Patani','Sapele','Udu','Ughelli North','Ughelli South',
    'Ukwuani','Uvwie','Warri North','Warri South','Warri South West','Other',
  ],
  'Ebonyi': [
    'Abakaliki','Afikpo North','Afikpo South','Ebonyi','Ezza North',
    'Ezza South','Ikwo','Ishielu','Ivo','Izzi','Ohaozara','Ohaukwu',
    'Onicha','Other',
  ],
  'Edo': [
    'Akoko-Edo','Egor','Esan Central','Esan North-East','Esan South-East',
    'Esan West','Etsako Central','Etsako East','Etsako West','Igueben',
    'Ikpoba-Okha','Orhionmwon','Oredo','Ovia North-East','Ovia South-West',
    'Owan East','Owan West','Uhunmwonde','Other',
  ],
  'Ekiti': [
    'Ado Ekiti','Efon','Ekiti East','Ekiti South-West','Ekiti West',
    'Emure','Gbonyin','Ido/Osi','Ijero','Ikere','Ikole','Ilejemeje',
    'Irepodun/Ifelodun','Ise/Orun','Moba','Oye','Other',
  ],
  'Enugu': [
    'Aninri','Awgu','Enugu East','Enugu North','Enugu South',
    'Ezeagu','Igbo Etiti','Igbo Eze North','Igbo Eze South','Isi Uzo',
    'Nkanu East','Nkanu West','Nsukka','Oji River','Udenu','Udi','Uzo Uwani',
    'Other',
  ],
  'Gombe': [
    'Akko','Balanga','Billiri','Dukku','Funakaye','Gombe','Kaltungo',
    'Kwami','Nafada','Shongom','Yamaltu/Deba','Other',
  ],
  'Imo': [
    'Aboh Mbaise','Ahiazu Mbaise','Ehime Mbano','Ezinihitte','Ideato North',
    'Ideato South','Ihitte/Uboma','Ikeduru','Isiala Mbano','Isu',
    'Mbaitoli','Ngor Okpala','Njaba','Nkwerre','Nwangele','Obowo',
    'Oguta','Ohaji/Egbema','Okigwe','Orlu','Orsu','Oru East','Oru West',
    'Owerri Municipal','Owerri North','Owerri West','Unuimo','Other',
  ],
  'Jigawa': [
    'Auyo','Babura','Biriniwa','Birnin Kudu','Buji','Dutse',
    'Gagarawa','Garki','Gumel','Guri','Gwaram','Gwiwa','Hadejia',
    'Jahun','Kafin Hausa','Kazaure','Kiri Kasamma','Kiyawa','Maigatari',
    'Malam Madori','Miga','Ringim','Roni','Sule Tankarkar','Taura',
    'Yankwashi','Other',
  ],
  'Kaduna': [
    'Birnin Gwari','Chikun','Giwa','Igabi','Ikara','Jaba',
    'Jema\'a','Kachia','Kaduna North','Kaduna South','Kagarko','Kajuru',
    'Kaura','Kauru','Kubau','Kudan','Lere','Makarfi','Sabon Gari',
    'Sanga','Soba','Zangon Kataf','Zaria','Other',
  ],
  'Kano': [
    'Ajingi','Albasu','Bagwai','Bebeji','Bichi','Bunkure','Dala',
    'Dambatta','Dawakin Kudu','Dawakin Tofa','Doguwa','Fagge','Gabasawa',
    'Garko','Garun Mallam','Gaya','Gezawa','Gwale','Gwarzo','Kabo',
    'Kano Municipal','Karaye','Kibiya','Kiru','Kumbotso','Kunchi',
    'Kura','Madobi','Makoda','Minjibir','Nassarawa','Rano','Rimin Gado',
    'Rogo','Shanono','Sumaila','Takai','Tarauni','Tofa','Tsanyawa',
    'Tudun Wada','Ungogo','Warawa','Wudil','Other',
  ],
  'Katsina': [
    'Bakori','Batagarawa','Batsari','Baure','Bindawa','Charanchi',
    'Dandume','Danja','Dan Musa','Daura','Dutsi','Dutsin-Ma','Faskari',
    'Funtua','Ingawa','Jibia','Kafur','Kaita','Kankara','Kankia',
    'Katsina','Kurfi','Kusada','Mai\'Adua','Malumfashi','Mani','Mashi',
    'Matazu','Musawa','Rimi','Sabuwa','Safana','Sandamu','Zango','Other',
  ],
  'Kebbi': [
    'Aleiro','Arewa Dandi','Argungu','Augie','Bagudo','Birnin Kebbi',
    'Bunza','Dandi','Fakai','Gwandu','Jega','Kalgo','Koko/Besse',
    'Maiyama','Ngaski','Sakaba','Shanga','Suru','Wasagu/Danko',
    'Yauri','Zuru','Other',
  ],
  'Kogi': [
    'Adavi','Ajaokuta','Ankpa','Bassa','Dekina','Ibaji','Idah',
    'Igalamela-Odolu','Ijumu','Kabba/Bunu','Kogi','Lokoja','Mopa-Muro',
    'Ofu','Ogori/Magongo','Okehi','Okene','Olamaboro','Omala',
    'Yagba East','Yagba West','Other',
  ],
  'Kwara': [
    'Asa','Baruten','Edu','Ekiti','Ifelodun','Ilorin East',
    'Ilorin South','Ilorin West','Irepodun','Isin','Kaiama',
    'Moro','Offa','Oke Ero','Oyun','Pategi','Other',
  ],
  'Nasarawa': [
    'Akwanga','Awe','Doma','Karu','Keana','Keffi','Kokona',
    'Lafia','Nasarawa','Nasarawa Egon','Obi','Toto','Wamba','Other',
  ],
  'Niger': [
    'Agaie','Agwara','Bida','Borgu','Bosso','Chanchaga','Edati',
    'Gbako','Gurara','Katcha','Kontagora','Lapai','Lavun','Magama',
    'Mariga','Mashegu','Mokwa','Moya','Paikoro','Rafi','Rijau',
    'Shiroro','Suleja','Tafa','Wushishi','Other',
  ],
  'Ogun': [
    'Abeokuta North','Abeokuta South','Ado-Odo/Ota','Egbado North',
    'Egbado South','Ewekoro','Ifo','Ijebu East','Ijebu North',
    'Ijebu North East','Ijebu Ode','Ikenne','Imeko Afon','Ipokia',
    'Obafemi Owode','Odeda','Odogbolu','Ogun Waterside','Remo North',
    'Sagamu','Other',
  ],
  'Ondo': [
    'Akoko North-East','Akoko North-West','Akoko South-East',
    'Akoko South-West','Akure North','Akure South','Ese Odo',
    'Idanre','Ifedore','Ilaje','Ile Oluji/Okeigbo','Irele',
    'Odigbo','Okitipupa','Ondo East','Ondo West','Ose','Owo','Other',
  ],
  'Osun': [
    'Aiyedaade','Aiyedire','Atakunmosa East','Atakunmosa West',
    'Boluwaduro','Boripe','Ede North','Ede South','Egbedore','Ejigbo',
    'Ife Central','Ife East','Ife North','Ife South','Ifedayo',
    'Ifelodun','Ila','Ilesa East','Ilesa West','Irepodun',
    'Irewole','Isokan','Iwo','Obokun','Odo Otin','Ola Oluwa',
    'Olorunda','Oriade','Orolu','Osogbo','Other',
  ],
  'Oyo': [
    'Afijio','Akinyele','Atiba','Atisbo','Egbeda','Ibadan North',
    'Ibadan North-East','Ibadan North-West','Ibadan South-East',
    'Ibadan South-West','Ibarapa Central','Ibarapa East','Ibarapa North',
    'Ido','Irepo','Iseyin','Itesiwaju','Iwajowa','Kajola','Lagelu',
    'Ogbomosho North','Ogbomosho South','Ogo Oluwa','Olorunsogo',
    'Oluyole','Ona Ara','Orelope','Ori Ire','Oyo East','Oyo West',
    'Saki East','Saki West','Surulere','Other',
  ],
  'Plateau': [
    'Barkin Ladi','Bassa','Bokkos','Jos East','Jos North','Jos South',
    'Kanam','Kanke','Langtang North','Langtang South','Mangu',
    'Mikang','Pankshin','Qua\'an Pan','Riyom','Shendam','Wase','Other',
  ],
  'Rivers': [
    'Abua/Odual','Ahoada East','Ahoada West','Akuku-Toru','Andoni',
    'Asari-Toru','Bonny','Degema','Eleme','Emouha','Etche','Gokana',
    'Ikwerre','Khana','Obio-Akpor','Ogba/Egbema/Ndoni','Ogu/Bolo',
    'Okrika','Omuma','Opobo/Nkoro','Oyigbo','Port Harcourt',
    'Tai','Other',
  ],
  'Sokoto': [
    'Binji','Bodinga','Dange Shuni','Gada','Goronyo','Gudu','Gwadabawa',
    'Illela','Isa','Kebbe','Kware','Rabah','Sabon Birni','Shagari',
    'Silame','Sokoto North','Sokoto South','Tambuwal','Tangaza',
    'Tureta','Wamako','Wurno','Yabo','Other',
  ],
  'Taraba': [
    'Ardo Kola','Bali','Donga','Gashaka','Gassol','Ibi','Jalingo',
    'Karim Lamido','Kumi','Lau','Sardauna','Takum','Ussa',
    'Wukari','Yorro','Zing','Other',
  ],
  'Yobe': [
    'Bade','Bursari','Damaturu','Fika','Fune','Geidam','Gujba',
    'Gulani','Jakusko','Karasuwa','Machina','Nangere','Nguru',
    'Potiskum','Tarmuwa','Yunusari','Yusufari','Other',
  ],
  'Zamfara': [
    'Anka','Bakura','Birnin Magaji/Kiyaw','Bukkuyum','Bungudu',
    'Gummi','Gusau','Kaura Namoda','Maradun','Maru','Shinkafi',
    'Talata Mafara','Tsafe','Zurmi','Other',
  ],

  // ── UAE ───────────────────────────────────────────────────────
  'Dubai': ['Downtown Dubai','Deira','Bur Dubai','Jumeirah','Marina','JLT','Business Bay','DIFC','Palm Jumeirah','Mirdif','Al Quoz','Karama','Other'],
  'Abu Dhabi': ['Abu Dhabi City','Al Ain','Khalifa City','Mohammed Bin Zayed City','Yas Island','Saadiyat Island','Other'],
  'Sharjah': ['Sharjah City','Khor Fakkan','Kalba','Other'],
  'Ajman': ['Ajman City','Al Jurf','Other'],
  'Ras Al Khaimah': ['RAK City','Al Hamra','Other'],

  // ── UK ────────────────────────────────────────────────────────
  'England': ['London','Manchester','Birmingham','Leeds','Liverpool','Sheffield','Bristol','Newcastle','Nottingham','Leicester','Coventry','Bradford','Other'],
  'Scotland': ['Edinburgh','Glasgow','Aberdeen','Dundee','Inverness','Other'],
  'Wales': ['Cardiff','Swansea','Newport','Bangor','Other'],
  'Northern Ireland': ['Belfast','Derry','Lisburn','Other'],

  // ── USA ───────────────────────────────────────────────────────
  'California': ['Los Angeles','San Francisco','San Diego','Sacramento','San Jose','Fresno','Oakland','Other'],
  'New York': ['New York City','Buffalo','Albany','Rochester','Syracuse','Other'],
  'Texas': ['Houston','Dallas','Austin','San Antonio','Fort Worth','El Paso','Other'],
  'Florida': ['Miami','Orlando','Tampa','Jacksonville','Fort Lauderdale','Other'],
  'Georgia': ['Atlanta','Savannah','Augusta','Columbus','Other'],
}
